<a href="https://colab.research.google.com/github/Amithchintu/-Numpy_Assignment/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

# Create a 3x3 NumPy array with random integers between 1 and 100, and then interchange its rows and columns.

# Step 1: Create the 3x3 Array
# We’ll use np.random.randint() to generate the array.

In [ ]:
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original array:\n", arr)

# Step 2: Interchange Rows and Columns
# We can use the transpose() method or the .T attribute to interchange the rows and columns.

In [ ]:
# Interchanging rows and columns
transposed_arr = arr.T
print("Transposed array:\n", transposed_arr)

# Complete Code
# Here’s the complete code to create and transpose the array:

In [ ]:
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original array:\n", arr)

# Interchanging rows and columns
transposed_arr = arr.T
print("Transposed array:\n", transposed_arr)

Original array:
 [[14 78 70]
 [93 17 17]
 [19 38 73]]
Transposed array:
 [[14 93 19]
 [78 17 38]
 [70 17 73]]


# Example Output
# The output will vary each time you run the code because of the random integers.


# This code snippet demonstrates how to create a 3x3 array with random integers and interchange its rows and columns using NumPy.

# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
# Let’s go through the steps to generate a 1D NumPy array with 10 elements and reshape it into a 2x5 array, then into a 5x2 array.

# Step 1: Generate a 1D NumPy Array with 10 Elements
# We’ll use np.arange() to create an array with 10 elements.

In [ ]:
import numpy as np

# Creating a 1D array with 10 elements
arr = np.arange(10)
print("Original 1D array:\n", arr)

# Step 2: Reshape the Array into a 2x5 Array
# We’ll use the reshape() method to change the shape of the array.

In [ ]:
# Reshaping the array into a 2x5 array
arr_2x5 = arr.reshape((2, 5))
print("Reshaped to 2x5 array:\n", arr_2x5)

# Step 3: Reshape the Array into a 5x2 Array
# We’ll again use the reshape() method to change the shape of the array.

In [ ]:
# Reshaping the array into a 5x2 array
arr_5x2 = arr_2x5.reshape((5, 2))
print("Reshaped to 5x2 array:\n", arr_5x2)

# Complete Code
# Here’s the complete code to generate and reshape the array:

In [ ]:
import numpy as np

# Creating a 1D array with 10 elements
arr = np.arange(10)
print("Original 1D array:\n", arr)

# Reshaping the array into a 2x5 array
arr_2x5 = arr.reshape((2, 5))
print("Reshaped to 2x5 array:\n", arr_2x5)

# Reshaping the array into a 5x2 array
arr_5x2 = arr_2x5.reshape((5, 2))
print("Reshaped to 5x2 array:\n", arr_5x2)

Original 1D array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped to 2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped to 5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# This code demonstrates how to create a 1D array and reshape it into different dimensions using NumPy.

# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


# Let’s create a 4x4 NumPy array with random float values and then add a border of zeros around it to form a 6x6 array.

# Step 1: Create the 4x4 Array with Random Float Values
# We’ll use np.random.rand() to generate the array with random float values between 0 and 1.

In [ ]:
import numpy as np

# Creating a 4x4 array with random float values
arr_4x4 = np.random.rand(4, 4)
print("Original 4x4 array:\n", arr_4x4)

# Step 2: Add a Border of Zeros
# We can use np.pad() to add a border of zeros around the array.

In [ ]:
# Adding a border of zeros around the 4x4 array
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print("6x6 array with border of zeros:\n", arr_6x6)

# Complete Code
# Here’s the complete code to create the 4x4 array and add a border of zeros:

In [ ]:
import numpy as np

# Creating a 4x4 array with random float values
arr_4x4 = np.random.rand(4, 4)
print("Original 4x4 array:\n", arr_4x4)

# Adding a border of zeros around the 4x4 array
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print("6x6 array with border of zeros:\n", arr_6x6)

Original 4x4 array:
 [[0.56638249 0.75880641 0.81001079 0.38044171]
 [0.8091549  0.11078407 0.48820193 0.82770919]
 [0.85790396 0.55674959 0.31701567 0.04921525]
 [0.14777236 0.00212956 0.13000026 0.23487079]]
6x6 array with border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.56638249 0.75880641 0.81001079 0.38044171 0.        ]
 [0.         0.8091549  0.11078407 0.48820193 0.82770919 0.        ]
 [0.         0.85790396 0.55674959 0.31701567 0.04921525 0.        ]
 [0.         0.14777236 0.00212956 0.13000026 0.23487079 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# Example Output
# The output will vary each time you run the code because of the random float values. Here’s an example output:

# This code demonstrates how to create a 4x4 array with random float values and add a border of zeros around it using NumPy.

# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

# Create an array of integers from 10 to 60 with a step of 5 using the np.arange() function in NumPy.

In [ ]:
import numpy as np

# Creating an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 65, 5)
print("Array with integers from 10 to 60 with step 5:\n", arr)

Array with integers from 10 to 60 with step 5:
 [10 15 20 25 30 35 40 45 50 55 60]


# Explanation
# np.arange(start, stop, step): This function generates an array with values starting from start up to (but not including) stop, with a specified step between each value.
# Parameters:
# start: The starting value of the sequence (inclusive).
# stop: The end value of the sequence (exclusive).
# step: The difference between each pair of consecutive values.

# This code snippet demonstrates how to create an array with a specified range and step size using NumPy.

# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

# Create a NumPy array of strings and apply different case transformations to each element:

In [ ]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)
swapcase_arr = np.char.swapcase(arr)

print("Original array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title case:", titlecase_arr)
print("Swap case:", swapcase_arr)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']
Swap case: ['PYTHON' 'NUMPY' 'PANDAS']


# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

# create a NumPy array of words and insert a space between each character of every word in the array:

In [ ]:
import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

print("Original array:", words)
print("Array with spaces:", spaced_words)

Original array: ['python' 'numpy' 'pandas']
Array with spaces: ['p y t h o n' 'n u m p y' 'p a n d a s']


# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

# Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division:

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

# Create a 5x5 identity matrix using NumPy and then extract its diagonal elements:

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

# generate a NumPy array of 100 random integers between 0 and 1000, and then find and display all the prime numbers in this array:

In [ ]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)

Random Integers:
 [264 702 276 616 761 125 329 603 359 376 941 778 280 383 579 174 124 762
 619 488 149 630 258 509 617  16 279 219 902  93 263 813 974 462 190  26
 897  29  17 633   2 951 653 884  84 251  22 541 657 637 372 508 437 108
 811 696 466 516 247 391 176 671 168 226 711  89 767 826 556 536 488 939
 917 253 890 799 401 686 824 688 210 644 904  84 156 584 655 934 948 640
 347 721 466 788 534 364 768 292 964 560]
Prime Numbers:
 [761, 359, 941, 383, 619, 149, 509, 617, 263, 29, 17, 2, 653, 251, 541, 811, 89, 401, 347]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

# create a NumPy array representing daily temperatures for a month and calculate the weekly averages:

In [ ]:
import numpy as np

# Generate a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 40, size=30)  # Example temperatures between 20°C and 40°C

# Calculate weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

print("Daily Temperatures:\n", daily_temperatures)
print("Weekly Averages:\n", weekly_averages)

Daily Temperatures:
 [23 20 27 39 33 34 21 33 35 24 23 31 33 23 37 23 23 36 24 27 23 39 23 25
 33 20 20 28 38 39]
Weekly Averages:
 [28.142857142857142, 28.857142857142858, 27.571428571428573, 26.857142857142858, 38.5]
